### ISSUE TITLE
Feature request: Allow option to not need double click

### ISSUE THREAD

**Issue by chrissound** [panzerdp/clipboardy#10]
Thank you so much for this extension! It's going to save me so much time!

I've tried to modify the code to not need the double click, but I get console errors with my change.

If anyone has any ideas / solutions - I'd be grateful!

**Comment by chrissound** [comment]
Here is my change:
```
diff --git a/scripts/stackoverflow/inject.js b/scripts/stackoverflow/inject.js
index b05b9c1..8df6263 100644
--- a/scripts/stackoverflow/inject.js
+++ b/scripts/stackoverflow/inject.js
@@ -30,7 +30,6 @@ chrome.storage.local.get(null, function (result) {
 			Array.from(document.getElementsByTagName('pre')) // get all code snippets
 				.forEach(function (block) {
 
-					block.addEventListener('dblclick', function (event) {
 						// Reference: http://stackoverflow.com/a/6462980/3485241
 
 						// Add snippet to range
@@ -69,10 +68,9 @@ chrome.storage.local.get(null, function (result) {
 						} catch (err) {
 							console.log('Failed to copy', err);
 						}
-					});
 				});
 
 			break;
 		}
 	}
-});
\ No newline at end of file
+});
```

**Comment by panzerdp** [comment]
@chrissound,
What exactly do you want to achieve?

**Comment by chrissound** [comment]
To be able to just right click on a code snippet and copy.

Right now, I have to double click, and then right click and copy.

**Comment by panzerdp** [comment]
@chrissound,
Where do you double click exactly? Please give me more details about the steps you're doing, and on what site.

**Comment by panzerdp** [comment]
@chrissound,
If you propose a modification, please do create a pull request so I can check the code.

**Comment by chrissound** [comment]
I've realized my mistake - so I don't think it's worth discussing further.

It might be useful to indicate HOW to actually use this though, maybe we can mention on the readme that a "double click" on the actual code block is the mechanism how to copy the code.

Anyway, thanks for making this!

**Comment by chrissound** [comment]
Oh my I am genuinely an idiot... This is the wrong project...
