### ISSUE TITLE
Automatically switch to background tab with code

### ISSUE THREAD

**Issue by pjpjq** [panzerdp/clipboardy#11]
I open a new tab with pastable code in the background (command + click on mac chrome), but it automatically switches to the tab instead.

**Comment by dosentmatter** [comment]
@wendingp, I'm having the same issue as well. For me, I've narrowed it down to clipboardy and chrono download manager extensions:
![clipboardy_chrono_download](https://user-images.githubusercontent.com/5732253/61737667-8d7e8480-ad3d-11e9-9996-f950f60e781d.gif)

I've used both of these extensions for a long time and I've only noticed this issue somewhat recently. I initially thought it was a chrome issue until I tried turning off all my extensions. Clipboardy was last updated May 25, 2017. Chrono was last updated July 11, 2018.

I am on Chrome Version 75.0.3770.142 (Official Build) (64-bit), macOS mojave 10.14.4.

It jumps to the tab even if I switch to a different application. It's very annoying. Does it happen to you with just clipboardy enabled or do you also use Chrono? Have you found any workarounds?

I don't see any errors in the dev console or background page console.

**Comment by pjpjq** [comment]
@dosentmatter I think it's a issue just caused by clipboardy cuz I don't use Chrono. Unfortunately I didn't find workarounds so I just uninstalled this extension...

**Comment by panzerdp** [comment]
@dosentmatter Thanks for the demo.
Should be fixed in 0.9.6.

**Comment by dosentmatter** [comment]
@panzerdp, thanks for fixing it. Confirmed that it works in 0.9.6 now.
