### ISSUE TITLE
Extension has stopped working (copy and paste icons missing) Chrome Version 85

### ISSUE THREAD

**Issue by hakonhagland** [panzerdp/clipboardy#17]
The extension has worked fine until last week. Now suddenly the layout on stackoverflow.com seems to have changed slightly and the extension is not working (copy icon is missing). I am using Chrome Version 85.0.4183.83 (Official Build) (64-bit). Here is a sample screenshot:

 
![clip](https://user-images.githubusercontent.com/6708379/91732416-7ea50b00-eba8-11ea-8c00-3daaa02e6ec3.png)

Any idea what is going on?

**Comment by andybrown73** [comment]
Came here to report the same issue.  Same Chrome version:  Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by panzerdp** [comment]
I've made the fix and pushed to Chrome storage a new version 0.9.7. It may take a few weeks to be reviewed.
