### ISSUE TITLE
Doesn't work on GitHub but works on StackOverflow

### ISSUE THREAD

**Issue by mmalchuk** [panzerdp/clipboardy#3]
Doesn't work on GitHub but works on StackOverflow
Can't find why, how this can be solved?

**Comment by panzerdp** [comment]
Hi @mmalchuk,
Thanks for your report.

For the latest 0.9.3 version it works fine on GitHub ReadMe pages.
What exactly does not work for you?

Thanks.

**Comment by mmalchuk** [comment]
I see, with READ.me it works :)
But it doesn't with source code itself. For example:
https://github.com/panzerdp/clipboardy/blob/master/src/js/github/init.js
I want to see 'copy' button from the plugin, but I need to select all the lines and use standard copy function.

**Comment by panzerdp** [comment]
@mmalchuk Sounds like a good feature request. I will think about an implementation for that.
Thanks.

**Comment by sepehr** [comment]
+1
