### ISSUE TITLE
Private Key is still public

### ISSUE THREAD

**Issue by ariporad** [panzerdp/clipboardy#5]
Hello @panzerdp!

This extension looks really cool, thanks for making it.

Sorry to bother you, but I just wanted you to know that your extension private key [is still visible](https://github.com/panzerdp/clipboardy/commit/a2993c0b9826967b5b78de75c582928d917a15b0).

**Comment by panzerdp** [comment]
Hey @ariporad,
This key was used only for testing, so it has no valuable meaning.
Thanks for the info.
