### ISSUE TITLE
Does not work on StackOverflow

### ISSUE THREAD

**Issue by sepehr** [panzerdp/clipboardy#8]
First, thank you so much for this!

Seems not working on StackOverflow though:  

![screen shot 2017-01-02 at 10 37 15 pm](https://cloud.githubusercontent.com/assets/23576/21594808/1e8f4260-d13c-11e6-9443-c2387fcd24dc.png)

I skimmed the page source and there were no clipboardy iframe injected. Any ideas how to fix it?

**Comment by panzerdp** [comment]
Hey @sepehr,

I tried and it works fine on stackoverflow.
Can you send me the link you're testing?

Thanks.

**Comment by sepehr** [comment]
Yeah sure, here's one for example:

https://stackoverflow.com/questions/41434307

I even disabled all other extensions, thinking that there might be a conflict; still nothing.

**Comment by panzerdp** [comment]
Haha,
That's because of https. If you try the same question on http, it works fine: http://stackoverflow.com/questions/41434307.

I will fix that. Thanks for reporting.

**Comment by panzerdp** [comment]
Fixed in version 0.9.4.
The new version is published in Chrome store.

**Comment by sepehr** [comment]
Great! thanks.
