### ISSUE TITLE
How do you add another url

### ISSUE THREAD

**Issue by JBaczuk** [panzerdp/clipboardy#9]
Hi nice extension!  I'm wondering how I can add a domain that the extension will work for.  I tried adding to `documentUrlPatterns[]` in `controller.js` and it doesn't appear to work.  The website I want uses `<code>` tags.

**Comment by chrissound** [comment]
The code also needs to be in  `<pre>` tags

**Comment by panzerdp** [comment]
@JBaczuk,
You need to add the URL pattern to `manifest.json` also.
